---
branches:
  - name: main
  - name: next
    channel: channel-next
  - name: beta
    channel: beta
    prerelease: true
  - name: dev
    channel: dev
    prerelease: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
        - BREAKING CHANGE
        - BREAKING CHANGES
        - BREAKING
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
        - BREAKING CHANGE
        - BREAKING CHANGES
        - BREAKING
      writerOpts:
        commitsSort:
        - subject
        - scope

  - - "@semantic-release/exec"
    - generateNotesCmd: |
        echo VERSION=v${nextRelease.version} >> $GITHUB_ENV

